### ISSUE TITLE
Access Wideners don't work

### ISSUE THREAD

**Issue by Chocohead** [minecraft-cursed-legacy/Example-Mod#3]
We've got Access Transformers though which are obviously much better. Needs to get fixed in Loom (which is not going to be a fun merge).

**Comment by Chocohead** [comment]
Related to Chocohead/Fabric-Loom#6

**Comment by valoeghese** [comment]
The mentioned issue is closed, is this issue closed?

**Comment by Chocohead** [comment]
Yeah this is fixed both in remapping dependencies which have AWs, and transforming ATs to AWs at compile time if the option is turned on to do so
